## BUILDER
FROM node:15 AS build
#ENV NODE_OPTIONS="--openssl-legacy-provider"
WORKDIR /home/node/app
COPY ./ ./
RUN npm install
RUN npm run build


## IMAGEN
FROM node:16-alpine3.15
#ENV NODE_OPTIONS="--openssl-legacy-provider"
WORKDIR /home/node/app
COPY package.json ./
COPY package-lock.json ./
COPY --from=build /home/node/app/.nuxt/ ./.nuxt
RUN apk --no-cache add curl
RUN npm ci --only=production
